### ISSUE TITLE
Is it possible to use it in the form builder, not the admin panel ?

### ISSUE THREAD

**Issue by yamakrane** [ysfkaya/filament-phone-input#13]
For some reason i get this when i use it in filament form builder:

Alpine Expression Error: **phoneInputFormComponent is not defined**

Expression: "phoneInputFormComponent({
                    getInputTelOptionsUsing: (intlTelInput) => ({"allowDropdown":true,"autoPlaceholder":"aggressive","customContainer":"","customPlaceholder":null,"dropdownContainer":null,"excludeCountries":[],"formatOnDisplay":true,"geoIpLookup":"ipinfo","initialCountry":"auto","localizedCountries":[],"nationalMode":true,"onlyCountries":[],"placeholderNumberType":"MOBILE","preferredCountries":["us","gb"],"separateDialCode":false,"displayNumberFormat":"NATIONAL","inputNumberFormat":"E164","focusNumberFormat":false,"utilsScript":"\/filament\/assets\/intl-tel-input-utils.js"}),
                    state: $wire.entangle('phone').defer,
                    inputID: 'phone',
                })"

 <input type=​"tel" x-data=​"phoneInputFormComponent({
                    getInputTelOptionsUsing:​ (intlTelInput)​ => ({"allowDropdown":​true,"autoPlaceholder":​"aggressive","customContainer":​"","customPlaceholder":​null,"dropdownContainer":​null,"excludeCountries":​[]​,"formatOnDisplay":​true,"geoIpLookup":​"ipinfo","initialCountry":​"auto","localizedCountries":​[]​,"nationalMode":​true,"onlyCountries":​[]​,"placeholderNumberType":​"MOBILE","preferredCountries":​["us","gb"]​,"separateDialCode":​false,"displayNumberFormat":​"NATIONAL","inputNumberFormat":​"E164","focusNumberFormat":​false,"utilsScript":​"\/​filament\/​assets\/​intl-tel-input-utils.js"}​)​,
                    state:​ $wire.entangle('phone')​.defer,
                    inputID:​ 'phone',
                }​)​" dusk=​"filament.forms.phone" id=​"phone" class=​"block w-full transition duration-75 rounded-lg shadow-sm focus:​border-primary-600 focus:​ring-1 focus:​ring-inset focus:​ring-primary-600 disabled:​opacity-70 border-gray-300">​
handleError @ module.esm.js:416
mo

**Comment by ysfkaya** [comment]
Please check this [discussion](https://github.com/ysfkaya/filament-phone-input/discussions/10#discussioncomment-5593751)

**Comment by yamakrane** [comment]
`As you see I don't use the form feature of Filament yet.

I'm thinking new way to usage with form feature it in the next version of this package. Maybe just we can add assets on the top of application's layout. Just like below

components/layouts/app.blade.php`

Is that mean, that we can't use it in Filament's form builder yet and we need to wait for v3 ? Thanks
