### ISSUE TITLE
Error when displaying flags with Multi-tenancy

### ISSUE THREAD

**Issue by rjbh1971** [ysfkaya/filament-phone-input#22]
I'm using the filament phone input library, I'm very happy but it doesn't show me the flags when using Multi-tenancy .

In the explorer console it shows me the error  "GET http://asp-apps-3.test/phone-input-flags.png 404 (Not Found)"

This error only shows when using Multi-tenancy

**Comment by ysfkaya** [comment]
This package provides some routes to access input flags.

```php
// FilamentPhoneInputServiceProvider.php

Route::get('/phone-input-flags.png', function () {
    return response()->file(__DIR__.'/../images/vendor/intl-tel-input/build/flags.png');
});

Route::get('/phone-input-flags@2x.png', function () {
    return response()->file(__DIR__.'/../images/vendor/intl-tel-input/build/flags@2x.png');
}); 
  ```   
  
I guess you need to be put the route on your tenant path (or domain based etc..)
