### ISSUE TITLE
Language Switch 

### ISSUE THREAD

**Issue by BadreddineZatout** [ysfkaya/filament-phone-input#3]
When I switch to Arabic, the drop-down menu doesn't show properly on the screen (overflow problem)

**Comment by ysfkaya** [comment]
Hi @BadreddineZatout.

I was checking this issue, but what exactly are we talking about here?

<img width="1306" alt="Screen Shot 2022-09-23 at 11 13 45" src="https://user-images.githubusercontent.com/16710972/191918618-efcaeee2-296e-4fcf-b532-4d232a7f69f3.png">

**Comment by BadreddineZatout** [comment]
try making the input on the left the menu will overflow

**Comment by BadreddineZatout** [comment]
@ysfkaya Here is the issue (and sometimes the flags won't show on the input)
![image](https://user-images.githubusercontent.com/57811383/191925196-bf8a72f4-40bc-413b-afd4-1776b0d23fa8.png)

**Comment by BadreddineZatout** [comment]
@ysfkaya there is also an issue in the table as you can see in the image below
![image](https://user-images.githubusercontent.com/57811383/191926595-66388894-175d-441c-899c-d415dc90a990.png)

**Comment by ysfkaya** [comment]
> @ysfkaya there is also an issue in the table as you can see in the image below ![image](https://user-images.githubusercontent.com/57811383/191926595-66388894-175d-441c-899c-d415dc90a990.png)

This plugin is not provide any table column yet. I can add it in next version but not now. But you can still use the [Laravel Phone](https://github.com/Propaganistas/Laravel-Phone#formatting) package for validation and formatting.

As for the other problem, I understand the problem and will try to fix it when I am available.

**Comment by ysfkaya** [comment]
Fixed and tagged as `1.1.2`
