### ISSUE TITLE
initialCountry method triggers unsavedChangesAlerts without actual changes

### ISSUE THREAD

**Issue by abournavaud** [ysfkaya/filament-phone-input#38]
Hello Ysfkaya,

I'm encountering an issue with the PhoneInput component when used in conjunction with Filament's unsavedChangesAlerts() feature. Specifically, the PhoneInput component appears to trigger an unsaved changes alert even if no modifications have been made to the input field, provided that the **initialCountry** method is used.

**Steps to Reproduce:**

1. Add the unsavedChangesAlerts() method in a panel configuration file.
2. Include a PhoneInput field in the form and initialize it with a country code using PhoneInput::make('phone')->initialCountry('us')
3. Navigate to the form in the Filament admin panel and observe that the unsaved changes alert is triggered even without any user interaction with the PhoneInput field.

Thank you for your assistance and for maintaining this useful component.

**Comment by ysfkaya** [comment]
Hey @abournavaud

I will try to deal with this problem as soon as possible.

**Comment by ysfkaya** [comment]
Hey @abournavaud

Now I have applied the steps you specified and I could not encounter a problem as you said. Are you sure that there is no other component in the form elements that triggers the unsaved changes alert event?

https://github.com/ysfkaya/filament-phone-input/assets/16710972/7e94dae9-0fea-4ed8-935f-55cd265b0311

**Comment by abournavaud** [comment]
Hey @ysfkaya,

I've just done some more research and the anomaly occurs in several cases.
I'm using ->initialCountry('FR'). When my phone number is saved in the format "+33606060606" or "+33 6 06 06 06 06" the  unsaved changes alert event is not triggered.
However, if the recorded format is "0606060606" or "06 06 06 06 06", the unsaved changes alert event will be triggered.
When I add ->inputNumberFormat(PhoneInputNumberType::NATIONAL), the unsaved changes alert event is triggered regardless of the format.

**Comment by ysfkaya** [comment]
Ok I have released a new version for this. You can check it by updating to version `2.3.5`

**Comment by abournavaud** [comment]
It works, thank you.
