### ISSUE TITLE
Issue with PhoneInput Component inside a Wizard

### ISSUE THREAD

**Issue by AkikiCharbel** [ysfkaya/filament-phone-input#40]
Hello,

I am encountering an issue with the PhoneInput component when used inside a wizard. The component functions correctly on the front end, however, problems arise during form submission or while using the state.

Specifically, even though the input field is filled, the validation incorrectly triggers and flags the field as required upon submission. Below is the code snippet where the issue occurs:

```
PhoneInputFilament::make('hello_word')
    ->required()
    ->afterStateUpdated(function($state, $get, $set){
        dd('hello world phone_state', $state);
    })
    ->live(onBlur: true)
```

Within the wizard setup, the above code does not produce any output, despite the fact that similar code used outside of the wizard (but with a different name) correctly outputs the result of dd().

Could there be something I am overlooking or a potential bug with how PhoneInput behaves inside a wizard?

Any guidance or assistance in resolving this issue would be greatly appreciated.

Thank you.

**Comment by ysfkaya** [comment]
What is the version of the package you are using?

**Comment by AkikiCharbel** [comment]
@ysfkaya I'm using the latest version

<img width="610" alt="Screenshot 2024-04-16 at 1 55 57 PM" src="https://github.com/ysfkaya/filament-phone-input/assets/94985836/80873c19-3f39-4afc-8fc6-82a4f1ba2b6a">

**Comment by ysfkaya** [comment]
@AkikiCharbel

I'm not sure if I fully understand the problem, but when I try the situation you mentioned via TextInput, it works just like the situation that occurs in PhoneInput. So this may be related to the Wizard component. I am sharing the form diagram I tested below.

Can you also check it this way. The `afterStateUpdated` function is triggered both when the step changes and in the blur state.

```php
public static function form(Form $form): Form
    {
        return $form
            ->columns(1)
            ->schema([
               Wizard::make([
                    Wizard\Step::make('step 1')->schema([
                        Forms\Components\TextInput::make('name')
                            ->required()
                            ->autofocus()
                            ->placeholder('Enter a name...')
                            ->helperText('This is the name of the user.'),

                        Forms\Components\TextInput::make('email')
                            ->required()
                            ->placeholder('Enter an email address...')
                            ->helperText('This is the email address of the user.'),

                        PhoneInput::make('phone')
                            // NOTE: Triggered when the phone number is blurred or step is changed
                            // ->afterStateUpdated(function($state, $get, $set){
                            //     dd('hello world phone_state', $state);
                            // })
                            ->live(onBlur: true)
                            ->label('Number'),
                    ]),
                    Wizard\Step::make('step 2')->schema([
                        Forms\Components\TextInput::make('password')
                            ->password()
                            // NOTE: Also, this one triggered when step is changed
                            ->afterStateUpdated(function($state, $get, $set){
                                dd('hello world password_state', $state);
                            })
                            ->dehydrated(fn ($operation) => $operation !== 'edit')
                            ->required(fn ($operation) => $operation !== 'edit'),
                    ]),
               ])
            ]);
    }
 ```

**Comment by ysfkaya** [comment]
I am closing this issue as there are no more replies. If the issue persists, start a discussion or contact me on discord

**Comment by aeq-dev** [comment]
Never-mind :)  Found this : https://github.com/ysfkaya/filament-phone-input/issues/28#issuecomment-2254490604
