### ISSUE TITLE
Cannot set default for phone number input

### ISSUE THREAD

**Issue by haron68** [ysfkaya/filament-phone-input#41]
Hi nice plugin but it doesn't seem like the helper method works for setting a default phone number.

### Code 
```
PhoneInput::make('contact_phone')
    ->default('+12223334444')
    ->required()
```

### Current
<img width="511" alt="image" src="https://github.com/ysfkaya/filament-phone-input/assets/27697689/9f822f72-7ec1-408f-9650-06ea15fab270">

### Expected
<img width="513" alt="image" src="https://github.com/ysfkaya/filament-phone-input/assets/27697689/ae2ff208-4274-491b-8a31-033f65035aa2">

**Comment by ysfkaya** [comment]
Hi @haron68 

I have tested now and it works well. You need to fill the `form` on `mount` method of your Livewire component.

```php

public function mount(): void
{
    $this->form->fill();
}

```

**Comment by ysfkaya** [comment]
I am closing this issue as there are no more replies. If the issue persists, start a discussion or contact me on discord

**Comment by sezohessen** [comment]
@ysfkaya  how can I save country code? code mean +1 for Us not storing US

**Comment by sezohessen** [comment]
@ysfkaya In the view or edit page its not showing the flag of the number despite of phone_country is exists
