### ISSUE TITLE
Incorrect Country Flag Display after Updating filament-phone-input to v3.1.1

### ISSUE THREAD

**Issue by devSviat** [ysfkaya/filament-phone-input#55]
After updating the `filament-phone-input` library from version 3.1.0 to 3.1.1, an issue has arisen with the display of country flags.

### Steps to Reproduce:

1. Update `filament-phone-input` to version 3.1.1.
2. Check the display of country flags in the component.

### Expected Behavior:
Country flags should display correctly.

### Actual Behavior:
Country flags do not display correctly.

### Screenshots:

- **Issue:**  
  ![issue](https://github.com/user-attachments/assets/5d7f94b6-85ef-4c7f-a398-f19076fa6cd2)

- **Correct Display:**  
  ![сorrect](https://github.com/user-attachments/assets/e5283254-36f5-4734-b7d1-1511fc41f6f8)

### Additional Information:
If changes in the `filament-phone-input.css` and `filament-phone-input.js` files are reverted, the flag display issue disappears, and they display correctly.

**Comment by ysfkaya** [comment]
Could you try this, clear your browser cache and check again

```bash
php artisan vendor:publish --tag="filament-phone-input-assets" --force
```

**Comment by devSviat** [comment]
I ran the command and cleared the cache, but the problem persists. If I revert the updates to the filament-phone-input.css and filament-phone-input.js files in version 3.1.1, the data displays correctly.
<img width="227" alt="bug" src="https://github.com/user-attachments/assets/45779bb0-1501-4386-94df-fc5ed7220547">

**Comment by ysfkaya** [comment]
Try this way too. intl-tel-input can also have this problem when assets are updated. Therefore you need to make sure that the assets are pulled back into your project correctly. I don't seem to have a problem right now

```bash
php artisan vendor:publish --tag="filament-phone-input-assets" --force ; php artisan filament:assets
```

**Comment by devSviat** [comment]
It helped solve my problem, thank you very much!
> ```shell
> php artisan vendor:publish --tag="filament-phone-input-assets" --force ; php artisan filament:assets
> ```
