### ISSUE TITLE
Error to show flag icon

### ISSUE THREAD

**Issue by Faridleo1998** [ysfkaya/filament-phone-input#56]
Today I update a package, but the flag icons not showing correctly.

Before, the flag icons showing correctly. I follow the all commands to install and publish assets.

![image](https://github.com/user-attachments/assets/0de4a885-594e-46c2-b95e-4cb8d82172fd)

**Comment by ysfkaya** [comment]
Same #55

**Comment by Faridleo1998** [comment]
> Same #55

I executed the commands , but not working :(
