### ISSUE TITLE
Default country not respected

### ISSUE THREAD

**Issue by danr1979** [ysfkaya/filament-phone-input#57]
I am on version 3.1.2.  My code is below:

```
PhoneInput::make('mobile')
    ->label('Mobile phone')
    ->countryStatePath('mobile_country')
    ->defaultCountry('GB')
    ->onlyCountries(['GB', 'JE', 'GG', 'IM', 'IE'])
    ->required()
```

Having put my code live I noticed that despite having 'GB' set as the default country, the 'IE' (Republic of Ireland) flag shows.  See attached image.

![image](https://github.com/user-attachments/assets/733c0b33-9936-4198-9301-6b228f3fadc8)

Any help or suggestions would be appreciated.

Thank you.

**Comment by ysfkaya** [comment]
Did you try `initialCountry`?

**Comment by danr1979** [comment]
I had missed that method.  I will try it.

Thank you for your help.

**Comment by danr1979** [comment]
That seems to have worked.  Thanks again.
