### ISSUE TITLE
Error Class "Js" not found

### ISSUE THREAD

**Issue by elegasoft** [ysfkaya/filament-phone-input#59]
### Description

When using the `filament-phone-input` plugin, the application encounters a `Class "Js" not found` error. The issue arises due to a missing import for the `Js` class in the Blade template located in `resources/views/phone-input.blade.php`. 

It appears that the plugin assumes the `Js` class is globally accessible, but it does not include a namespace or reference the correct version of the Laravel `Js` class. As a result, the error occurs during rendering.

This issue seems to be related to a conflict between the `Filament\Support\Assets\Js` class and Laravel's native `Illuminate\Support\Js` class. In this case, the application needs the Laravel `Illuminate\Support\Js` class, but it is not imported in the Blade template where it is used.

---

### Steps to Reproduce
1. Use PHP 8.3.14, Laravel 11.35.0, and FilamentPHP v3.2.130
2. Install and enable the `filament-phone-input` plugin.
3. Attempt to load a page where the `phone-input` component is used, such as:
```php
use Ysfkaya\FilamentPhoneInput\Forms\PhoneInput;

$form->schema([
    PhoneInput::make('number')
        ->label(__('Phone Number'))
        ->required(),
])
```
4. The application throws the error: `Class "Js" not found in: /vendor/ysfkaya/filament-phone-input/resources/views/phone-input.blade.php:25`.

---

### Current Behavior

The application fails to render the page and provides the given error.

---

### Expected Behavior

The `phone-input.blade.php` template should correctly use the Laravel `Illuminate\Support\Js` class to compile the JavaScript variables, allowing the application to render without error.

---

### Suggested Fix

The template file in the `filament-phone-input` plugin needs to include the correct namespace for the `Js` class. Specifically, it should explicitly use the Laravel `Illuminate\Support\Js` class by adding the proper import statement, like so:

```php
// resources/views/phone-input.blade.php
@php
    use Filament\Support\Facades\FilamentView;
    use Illuminate\Support\Js; // This use statement should be added at line 3
    
    ...
```

This ensures that the correct `Js` class is used when compiling JavaScript variables, avoiding conflicts with other packages (e.g., `Filament\Support\Assets\Js`).

---

### Environment Details
- **PHP Version:** 8.3.14
- **Laravel Version:** 11.35.0
- **Plugin Version:** `ysfkaya/filament-phone-input`
- **Filament Version:** 3.2.130

---

### Additional Context

This error occurs in the following file:
`vendor/ysfkaya/filament-phone-input/resources/views/phone-input.blade.php`.

It appears that other Laravel developers may encounter the same issue if their environment requires Laravel's `Js` class instead of Filament's `Js` class.

Thank you for reviewing this issue. Please let me know if additional information is required!

**Comment by ysfkaya** [comment]
Thank you for your detailed explanation and support. Merged.
